### ISSUE TITLE
ICASR org logo

### ISSUE THREAD

**Issue by hash-bang** [icasr/icasr.github.io#1]
I feel the main ICASR org should have a logo show it is more prominent in the GitHub feed.

My attempt:

![icasr](https://user-images.githubusercontent.com/624527/31722380-d36e87d0-b413-11e7-9ae5-ba2c7fd4c0e6.png)

[SVG file](https://github.com/icasr/icasr.github.io/files/1394821/icasr.svg.txt)

**Comment by gertvv** [comment]
Up now
